"""Remove id of class membership and add composite pkey of (user_id, class_id)

Revision ID: 513bcebbc7ba
Revises: 1836b327112d
Create Date: 2020-06-06 17:43:07.857088

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '513bcebbc7ba'
down_revision = '1836b327112d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
