"""Convert tasks due date to date instead of datetime

Revision ID: 6dd141dc1c7d
Revises: 825d38d21af9
Create Date: 2020-06-09 15:21:16.876542

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6dd141dc1c7d'
down_revision = '825d38d21af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
