"""Add task and convert structures to enum

Revision ID: 825d38d21af9
Revises: 513bcebbc7ba
Create Date: 2020-06-09 12:05:42.586257

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '825d38d21af9'
down_revision = '513bcebbc7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('HOMEWORK', 'CLASSWORK', 'REVISION', name='tasktype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
